version: "3.1"
services:
    mysql:
        image: mysql:8.0
        container_name: jobeet-mysql
        working_dir: /app
        volumes:
            - .:/app
        environment:
            - MYSQL_ROOT_PASSWORD=onza_83
            - MYSQL_DATABASE=jobeet1
            - MYSQL_USER=symjobeet
            - MYSQL_PASSWORD=Casperonza_83
        ports:
            - 3307:3307

    webserver:
        image: nginx:alpine
        container_name: jobeet-webserver
        working_dir: /app
        volumes:
            - .:/app
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80

    php-fpm:
        build: docker/php-fpm
        container_name: jobeet-php-fpm
        working_dir: /app
        volumes:
            - .:/app
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
